### ISSUE TITLE
Getting error when trying to run StyleGAN2 models

### ISSUE THREAD

**Issue by erz0r** [harskish/ganspace#17]
Currently trying to play around with this as a little experiment, but whenever I try to run the StyleGAN2 interactive models, I get the following runtime error: 

`RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR`

I believe I may not have correctly configured/set up the StyleGAN2 installation from the page, as when I run the command prompt for VS2017, I can't even use Anaconda correctly, but I can get through the other steps fine.

I'm on a RTX 2070 and a Ryzen 5 3600.

**Comment by harskish** [comment]
Hi, sorry for the late reply.

This seems like a problem with your environment, and not an issue with ganspace per se - I've never seen this error before.
The error you mentioned with anaconda not being usabe in VS2017 is surely part of it. You might have to run conda init in that terminal. Also, make sure that the cuda version you have installed on your system matches the version expected (10.1).

**Comment by ghost** [comment]
Also see this error with conda installation on windows following the readme. 
```
"...\models\stylegan2\stylegan2-pytorch\model.py", line 273, in forward
    out = F.conv2d(input, weight, padding=self.padding, groups=batch)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```  

Also tried   torch.backends.cudnn.enabled = False but it fails in some .cu files.

**Comment by ghost** [comment]
I tried `python visualize.py --model=StyleGAN2 --class=ffhq --use_w --layer=style -b=10_000` and it works nicely. Only `interactive.py` fails.

**Comment by ima9ine** [comment]
same here

**Comment by negon** [comment]
did anybody find a solution for this, I have tried with CUDA 11.x with both NVIDIA 510 and 470 but nothing works, always just CUDNN_STATUS_MAPPING_ERROR.
Card is RTX 3070 with 11GB memory
