### ISSUE TITLE
RuntimeError: cuda runtime error (1) : invalid argument at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:29

### ISSUE THREAD

**Issue by ChengXuanhao** [harskish/ganspace#64]
hello，McFredward，I encountered a problem, as shown in the following sentences：
Two windows will appear and then flash back.
How to solve this problem？
D:\python\miniconda\envs\ganspace\python.exe E:/新电脑文件/论文/图纸生成/生成多角度二维图/gan-space/ganspace-master-ada/ganspace/interactive.py
StyleGAN2: Optimized CUDA op FusedLeakyReLU not available, using native PyTorch fallback.
StyleGAN2: Optimized CUDA op UpFirDn2d not available, using native PyTorch fallback.
No layer 'g_mapping' in StyleGAN2-ada. Assuming you meant 'mapping'
No layer 'g_mapping' in StyleGAN2-ada. Assuming you meant 'mapping'
1.8.0+cu111
Setting up PyTorch plugin "bias_act_plugin"... D:\python\miniconda\envs\ganspace\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... D:\python\miniconda\envs\ganspace\lib\site-packages\torch\utils\cpp_extension.py:304: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Done.
Loaded components for ffhq from E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\cache\components\stylegan2-ada-ffhq_mapping_ipca_c80_n300000.npz
Seed: 1928965846
Using GPU 0
THCudaCheck FAIL file=C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu line=29 error=1 : invalid argument
Traceback (most recent call last):
File "E:/新电脑文件/论文/图纸生成/生成多角度二维图/gan-space/ganspace-master-ada/ganspace/interactive.py", line 655, in
on_draw()
File "E:/新电脑文件/论文/图纸生成/生成多角度二维图/gan-space/ganspace-master-ada/ganspace/interactive.py", line 475, in on_draw
img = model.forward(z_final).clamp(0.0, 1.0)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\wrappers.py", line 203, in forward
img = self.model.synthesis.forward(x, noise_mode='const',force_fp32= self.device.type == 'cpu')
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\training\networks.py", line 471, in forward
x, img = block(x, img, cur_ws, **block_kwargs)
File "D:\python\miniconda\envs\ganspace\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\training\networks.py", line 398, in forward
x = self.conv1(x, next(w_iter), fused_modconv=fused_modconv, **layer_kwargs)
File "D:\python\miniconda\envs\ganspace\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
result = self.forward(*input, **kwargs)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\training\networks.py", line 300, in forward
padding=self.padding, resample_filter=self.resample_filter, flip_weight=flip_weight, fused_modconv=fused_modconv)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\torch_utils\misc.py", line 101, in decorator
return fn(*args, **kwargs)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\training\networks.py", line 80, in modulated_conv2d
x = conv2d_resample.conv2d_resample(x=x, w=w.to(x.dtype), f=resample_filter, up=up, down=down, padding=padding, groups=batch_size, flip_weight=flip_weight)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\torch_utils\misc.py", line 101, in decorator
return fn(*args, **kwargs)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\torch_utils\ops\conv2d_resample.py", line 147, in conv2d_resample
return _conv2d_wrapper(x=x, w=w, padding=[py0,px0], groups=groups, flip_weight=flip_weight)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\torch_utils\ops\conv2d_resample.py", line 54, in _conv2d_wrapper
return op(x, w, stride=stride, padding=padding, groups=groups)
File "E:\新电脑文件\论文\图纸生成\生成多角度二维图\gan-space\ganspace-master-ada\ganspace\models\stylegan2_ada\stylegan2-ada-pytorch\torch_utils\ops\conv2d_gradfix.py", line 38, in conv2d
return torch.nn.functional.conv2d(input=input, weight=weight, bias=bias, stride=stride, padding=padding, dilation=dilation, groups=groups)
RuntimeError: cuda runtime error (1) : invalid argument at C:/w/b/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:29

Process finished with exit code 1

**Comment by ChengXuanhao** [comment]
I solved this problem in another way. I can't run interactive.py on 3080ti and cuda11. Later, I bought a new computer and successfully ran interactive.py on 2080 and cuda10.1 At present, this program may only be used for low version GPU graphics cards, such as 10 series and 20 series. Then the 30 series cannot run successfully.
